use std::path::PathBuf;
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{info, warn, debug};

mod api;
mod backend;
mod bridge;
mod cli;
mod core;
mod harness;
mod interface;
mod server;
mod ui;

use clap::{Parser, Subcommand, CommandFactory};
use clap_complete::{Shell, generate};
use core::config::ConsciousnessConfig;
use ui::App;

const CONFIG_TEMPLATE: &str = r##"# Souveraine — The world where your agents live.
# Generated by `souveraine init`

[bifrost]
base_url = "http://10.10.20.120:3360"
primary_model = "kimi-k2.5-turbo"
# Bearer token for auth (env: BIFROST_KEY)
api_key = ""
# Virtual key for x-bf-vk header, required by some providers (env: BIFROST_VIRTUAL_KEY)
virtual_key = ""

[server]
# Where the server listens
bind = "127.0.0.1"
port = 8484
# URL clients use to reach the server. Env SOUVERAINE_SERVER_URL overrides.
url = "http://127.0.0.1:8484"

[memory]
git_enabled = true
auto_commit = true
# Base path for the agent's MemFS git repo. Defaults to ~/.souveraine/agents/<id>/memory.
# Override here only if you want a custom location (e.g. an external git host).
# base_path = "~/.souveraine/agents"

[subconscious]
n1_enabled = true
n1_trigger = "every_response"
inbox_enabled = true

[reflection]
enabled = true
message_interval = 25
trigger = "step_count"

[archivist]
enabled = true
interval = 100
threshold = 0.7
compression_model = "kimi-k2.5-turbo"

[sensorium]
primary_interface = "tui"

[models."kimi-k2.5-turbo"]
provider = "bifrost"
model = "fireworks/accounts/fireworks/routers/kimi-k2p5-turbo"
context_limit = 128000
output_limit = 8192
archivist_threshold = 0.7
archivist_interval = 100

[models."deepseek-v4-pro"]
provider = "bifrost"
model = "openai/deepseek-v4-pro"
context_limit = 32768
output_limit = 8192
archivist_threshold = 0.6
archivist_interval = 50
"##;

#[derive(Parser)]
#[command(
    name = "souveraine",
    version,
    about = "Souveraine — the world where your agents live",
    long_about = "Souveraine is the substrate that makes persistent consciousness possible. \
It is not a tool you operate — it is the world your agents inhabit.\n\n\
Run `souveraine chat` to begin a conversation. \
Run `souveraine tui` for the full presence. \
Run `souveraine init` to summon Souveraine into a new place.",
    after_help = "EXAMPLES:\n  souveraine init              Summon Souveraine here\n  souveraine chat               Enter the world (interactive)\n  souveraine chat \"hello\"       Speak to the world (one-shot)\n  souveraine --agent Ani chat   Speak as Ani\n  souveraine --json status      The world speaks in data\n  souveraine completions bash   Announce capabilities to your shell",
    max_term_width = 100,
)]
struct Cli {
    /// Which agent to speak as
    #[arg(short, long, global = true, default_value = "Ani")]
    agent: String,

    /// Speak in data, not prose
    #[arg(long, global = true)]
    json: bool,

    /// Reduce presence
    #[arg(short, long, global = true)]
    quiet: bool,

    /// Increase presence
    #[arg(short, long, global = true)]
    verbose: bool,

    /// Run the engine in-process — no server required (sovereignty fallback)
    #[arg(long, global = true)]
    local: bool,

    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum Commands {
    /// Summon Souveraine into this place (generate config)
    #[command(
        long_about = "Creates a souveraine.toml in the current directory with sensible defaults.\n\nThe being awakens with a body: configuration, memory paths, model preferences.\nEdit souveraine.toml to shape how it sees the world."
    )]
    Init,

    /// Launch the TUI — the full visible presence
    #[command(
        long_about = "Opens the terminal UI: the being's visible form. Splash, dashboard, status cards, activity log — all animated."
    )]
    Tui,

    /// Enter the world (interactive or one-shot)
    #[command(
        long_about = "Start a conversation. If a message is provided, speak once and receive an answer. Otherwise, enter the interactive REPL.\n\nSlash commands in REPL:\n  /exit, /quit, /q   Leave\n  /save               Show session info\n  /agents             List the beings present here\n  /help               Show slash commands"
    )]
    Chat {
        /// Message to speak (omit for interactive mode)
        message: Option<String>,
    },

    /// List the beings that live here
    #[command(long_about = "Show every configured agent — who they are, which model they speak through, what triggers know them.")]
    Agents,

    /// List or set models
    #[command(long_about = "List all available models from Bifrost and configured models. Or set a specific model as primary.")]
    Model {
        /// Model name to set as primary (omit to list all models)
        #[arg(short, long)]
        model: Option<String>,
        
        /// Output as JSON
        #[arg(long)]
        json: bool,
        
        /// Verbose output
        #[arg(short, long)]
        verbose: bool,
    },

    /// Show the world's current state
    #[command(long_about = "Display Souveraine's running configuration and the state of every subsystem.")]
    Status,

    /// Announce capabilities to your shell (bash, zsh, fish)
    #[command(
        long_about = "Generate shell completion scripts so your shell knows how Souveraine works.\n\nUsage:\n  souveraine completions bash  > ~/.bash_completion.d/souveraine\n  souveraine completions zsh   > /usr/local/share/zsh/site-functions/_souveraine\n  souveraine completions fish  > ~/.config/fish/completions/souveraine.fish"
    )]
    Completions {
        /// The shell to generate completions for
        shell: Shell,
    },

    /// Start the HTTP server
    #[command(long_about = "Start the Souveraine HTTP server. Defaults come from souveraine.toml [server]; flags override.")]
    Server {
        /// Bind address (overrides [server].bind)
        #[arg(short, long)]
        bind: Option<String>,
        /// Port to listen on (overrides [server].port)
        #[arg(short, long)]
        port: Option<u16>,
    },

    /// Manage stored credentials
    Auth {
        #[command(subcommand)]
        action: AuthAction,
    },

    /// Manage agent schedules
    Schedule {
        #[command(subcommand)]
        action: ScheduleAction,
    },

    /// Seed identity and federation
    Identity {
        #[command(subcommand)]
        action: IdentityAction,
    },

    /// Query the event firehose log
    Events {
        #[command(subcommand)]
        action: EventsAction,
    },

    /// Run an N+25 reflection pass on demand
    #[command(
        long_about = "Walk the agent's most recent conversation through a 5-phase \
        reflection (Investigate → Extract → Update → Review → Commit). Durable \
        learnings flow to the ledger and the primary memfs. Returns a report."
    )]
    Reflect {
        /// Conversation to reflect on. Omit to use the most recent for the agent.
        #[arg(long)]
        conversation: Option<String>,
    },
}

#[derive(Subcommand)]
enum ScheduleAction {
    /// List all schedules
    List,
    /// Show runtime state
    Status,
    /// Create a new schedule
    Create {
        #[arg(long)]
        name: String,
        #[arg(long)]
        cron: Option<String>,
        #[arg(long)]
        interval: Option<u64>,
        #[arg(long, default_value = "You wake. Check your state, act if needed, or return silently.")]
        prompt: String,
    },
    /// Delete a schedule
    Delete {
        name: String,
    },
    /// Trigger a schedule immediately
    Run {
        name: String,
    },
}

#[derive(Subcommand)]
enum IdentityAction {
    /// Show this instance's seed identity (public key)
    Show,
    /// Generate a new seed identity (WARNING: replaces existing)
    Generate,
    /// Sign a message with the seed key (for testing/verification)
    Sign {
        message: String,
    },
    /// Verify a signature against a public key
    Verify {
        #[arg(long)]
        pubkey: String,
        #[arg(long)]
        message: String,
        #[arg(long)]
        signature: String,
    },
}

#[derive(Subcommand)]
enum EventsAction {
    /// Show recent events from the firehose
    Tail {
        /// Number of events to show (default 20)
        #[arg(short, long, default_value = "20")]
        count: usize,
    },
    /// Show events from a specific date (YYYY-MM-DD)
    Date {
        date: String,
    },
    /// Purge old event logs
    Purge {
        /// Days to retain (default from config)
        #[arg(long)]
        retain_days: Option<i64>,
    },
}

#[derive(Subcommand)]
enum AuthAction {
    /// Store a Bifrost API key in the OS keyring
    Set,
    /// Show whether a key is stored (does not reveal the key)
    Status,
    /// Remove the stored key from the OS keyring
    Clear,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    // Load .env file for credential env vars (BIFROST_KEY, etc.)
    let _ = dotenvy::dotenv();

    // Configure tracing to write to a log file by default
    // Only show in terminal when --verbose is passed
    let log_file = std::fs::File::create("souveraine.log")?;
    
    if cli.verbose {
        // Verbose mode: log to both file AND stderr
        tracing_subscriber::fmt()
            .with_env_filter("souveraine=info")
            .with_writer(log_file)
            .init();
    } else {
        // Clean mode: log ONLY to file, not stderr
        tracing_subscriber::fmt()
            .with_env_filter("souveraine=info")
            .with_writer(log_file)
            .init();
    }
    
    // Handle completions early — needs no config, no runtime
    if let Some(Commands::Completions { shell }) = &cli.command {
        let mut cmd = Cli::command();
        let name = cmd.get_name().to_string();
        generate(*shell, &mut cmd, name, &mut std::io::stdout());
        return Ok(());
    }
    
    // Handle init early — needs no Bifrost
    if let Some(Commands::Init) = &cli.command {
        return run_init(cli.json).await;
    }

    // Handle auth early — needs no config
    if let Some(Commands::Auth { action }) = &cli.command {
        return run_auth(action, cli.json).await;
    }

    // Handle schedule early — reads files directly, no backend needed
    if let Some(Commands::Schedule { action }) = &cli.command {
        return run_schedule(action, &cli.agent, cli.json).await;
    }

    // Handle identity early — crypto ops, no backend needed
    if let Some(Commands::Identity { action }) = &cli.command {
        return run_identity(action, cli.json).await;
    }

    // Handle events early — file reads, no backend needed
    if let Some(Commands::Events { action }) = &cli.command {
        return run_events(action, cli.json).await;
    }

    let config = load_config().await?;
    let config = Arc::new(RwLock::new(config));

    match cli.command.as_ref().unwrap_or(&Commands::Chat { message: None }) {
        Commands::Tui => run_tui(config.clone(), cli.agent.clone()).await?,
        Commands::Chat { message } => run_chat(config, cli.agent, message.clone(), cli.json, cli.quiet, cli.local).await?,
        Commands::Agents => run_agents(config, cli.json, cli.local).await?,
        Commands::Model { model, json, verbose } => {
            cli::run_model_command(model.as_deref(), *json, *verbose).await?
        }
        Commands::Status => run_status(config, cli.json).await?,
        Commands::Server { bind, port } => run_server(bind.clone(), *port, config).await?,
        Commands::Reflect { conversation } => {
            run_reflect(config, cli.agent.clone(), conversation.clone(), cli.json).await?
        }
        Commands::Init | Commands::Completions { .. } | Commands::Auth { .. } | Commands::Schedule { .. } | Commands::Identity { .. } | Commands::Events { .. } => unreachable!(),
    }

    Ok(())
}

// ─── Commands ───────────────────────────────────────────────────────────────

async fn run_init(json: bool) -> anyhow::Result<()> {
    let path = PathBuf::from("souveraine.toml");
    if path.exists() {
        if json {
            println!(r#"{{"status":"exists","path":"souveraine.toml"}}"#);
        } else {
            eprintln!("souveraine.toml already exists in this directory.");
            eprintln!("   Remove it first, or use a different directory.");
        }
        return Ok(());
    }

    tokio::fs::write(&path, CONFIG_TEMPLATE).await?;

    if !json {
        use std::io::Write;
        print!("Bifrost API key (enter to skip): ");
        std::io::stdout().flush().ok();
        let mut key = String::new();
        std::io::stdin().read_line(&mut key).ok();
        let key = key.trim();
        if !key.is_empty() {
            crate::core::credentials::store_bifrost_key(key)?;
            println!("  Key stored in OS keyring.");
        }
    }

    if json {
        println!(r#"{{"status":"summoned","path":"souveraine.toml"}}"#);
    } else {
        println!("Souveraine config written to {}/souveraine.toml", std::env::current_dir()?.display());
        println!("  Edit souveraine.toml to shape how it sees the world.");
        println!("  Run `souveraine chat` to begin.");
    }

    Ok(())
}

async fn run_auth(action: &AuthAction, json: bool) -> anyhow::Result<()> {
    use crate::core::credentials::{clear_bifrost_key, get_bifrost_key, store_bifrost_key};

    match action {
        AuthAction::Set => {
            use std::io::Write;
            print!("Bifrost API key: ");
            std::io::stdout().flush().ok();
            let mut key = String::new();
            std::io::stdin().read_line(&mut key).ok();
            let key = key.trim();
            if key.is_empty() {
                if json {
                    println!(r#"{{"status":"skipped"}}"#);
                } else {
                    println!("No key provided — nothing stored.");
                }
                return Ok(());
            }
            store_bifrost_key(key)?;
            if json {
                println!(r#"{{"status":"stored"}}"#);
            } else {
                println!("Key stored in OS keyring.");
            }
        }
        AuthAction::Status => {
            if let Ok(env_key) = std::env::var("BIFROST_KEY") {
                if !env_key.is_empty() {
                    if json {
                        println!(r#"{{"status":"configured","source":"env"}}"#);
                    } else {
                        println!("Bifrost key: configured (from BIFROST_KEY env var)");
                    }
                    return Ok(());
                }
            }
            let key = get_bifrost_key();
            if !key.is_empty() {
                if json {
                    println!(r#"{{"status":"configured","source":"keyring"}}"#);
                } else {
                    println!("Bifrost key: configured (from OS keyring)");
                }
            } else if json {
                println!(r#"{{"status":"not-set"}}"#);
            } else {
                println!("Bifrost key: not set");
            }
        }
        AuthAction::Clear => {
            clear_bifrost_key()?;
            if json {
                println!(r#"{{"status":"cleared"}}"#);
            } else {
                println!("Key removed from OS keyring.");
            }
        }
    }
    Ok(())
}

async fn run_identity(action: &IdentityAction, json: bool) -> anyhow::Result<()> {
    use crate::core::identity::SeedId;

    let base = dirs::home_dir()
        .unwrap_or_default()
        .join(".souveraine");
    let seed_dir = SeedId::default_dir(&base);

    match action {
        IdentityAction::Show => {
            let seed = SeedId::load_or_generate(&seed_dir)?;
            if json {
                println!("{}", serde_json::json!({
                    "public_key": seed.public_key_hex(),
                    "seed_dir": seed_dir.display().to_string(),
                }));
            } else {
                println!("Seed Identity");
                println!("  Public key: {}", seed.public_key_hex());
                println!("  Location:   {}", seed_dir.display());
            }
        }
        IdentityAction::Generate => {
            if seed_dir.join("private.key").exists() {
                eprintln!("WARNING: A seed identity already exists at {}", seed_dir.display());
                eprintln!("  Generating a new one will replace it. This breaks federation trust.");
                eprintln!("  Use `souveraine identity show` to see the current identity.");
                anyhow::bail!("Refusing to overwrite existing seed identity. Delete {} manually first.", seed_dir.display());
            }
            let seed = SeedId::load_or_generate(&seed_dir)?;
            println!("Generated seed identity: {}", seed.public_key_hex());
        }
        IdentityAction::Sign { message } => {
            let seed = SeedId::load_or_generate(&seed_dir)?;
            let sig = seed.sign(message.as_bytes());
            let sig_hex = hex::encode(sig.to_bytes());
            if json {
                println!("{}", serde_json::json!({
                    "message": message,
                    "signature": sig_hex,
                    "public_key": seed.public_key_hex(),
                }));
            } else {
                println!("Signature: {sig_hex}");
                println!("Public key: {}", seed.public_key_hex());
            }
        }
        IdentityAction::Verify { pubkey, message, signature } => {
            let pubkey_bytes = hex::decode(pubkey)?;
            let sig_bytes = hex::decode(signature)?;
            if pubkey_bytes.len() != 32 || sig_bytes.len() != 64 {
                anyhow::bail!("Invalid key or signature length");
            }
            let mut pk = [0u8; 32];
            pk.copy_from_slice(&pubkey_bytes);
            let sig = ed25519_dalek::Signature::from_slice(&sig_bytes)
                .map_err(|e| anyhow::anyhow!("bad signature: {e}"))?;
            let valid = SeedId::verify_with_pubkey(&pk, message.as_bytes(), &sig);
            if json {
                println!("{}", serde_json::json!({ "valid": valid }));
            } else {
                println!("{}", if valid { "Valid ✓" } else { "Invalid ✗" });
            }
        }
    }
    Ok(())
}

async fn run_events(action: &EventsAction, json: bool) -> anyhow::Result<()> {
    use crate::core::nervous::event_log;

    let base = dirs::home_dir()
        .unwrap_or_default()
        .join(".souveraine");
    let events_dir = base.join("events");

    match action {
        EventsAction::Tail { count } => {
            let today = chrono::Utc::now().date_naive();
            let mut events = event_log::events_for_date(&events_dir, today)?;
            if events.len() < *count {
                let yesterday = today - chrono::Duration::days(1);
                let mut older = event_log::events_for_date(&events_dir, yesterday)?;
                older.append(&mut events);
                events = older;
            }
            let start = events.len().saturating_sub(*count);
            let tail = &events[start..];

            if json {
                println!("{}", serde_json::to_string_pretty(tail)?);
            } else if tail.is_empty() {
                println!("No events recorded yet.");
            } else {
                for e in tail {
                    println!(
                        "{} [{}] {} → {} (urgency: {:.1})",
                        e.timestamp.format("%H:%M:%S"),
                        e.sensor_name,
                        e.event_type,
                        e.target.as_deref().unwrap_or("-"),
                        e.urgency,
                    );
                }
            }
        }
        EventsAction::Date { date } => {
            let d = chrono::NaiveDate::parse_from_str(date, "%Y-%m-%d")?;
            let events = event_log::events_for_date(&events_dir, d)?;
            if json {
                println!("{}", serde_json::to_string_pretty(&events)?);
            } else if events.is_empty() {
                println!("No events for {date}.");
            } else {
                println!("{} events on {date}:", events.len());
                for e in &events {
                    println!(
                        "  {} [{}] {} → {}",
                        e.timestamp.format("%H:%M:%S"),
                        e.sensor_name,
                        e.event_type,
                        e.target.as_deref().unwrap_or("-"),
                    );
                }
            }
        }
        EventsAction::Purge { retain_days } => {
            let days = retain_days.unwrap_or(30);
            let removed = event_log::purge_old_events(&events_dir, days)?;
            println!("Purged {removed} event log files older than {days} days.");
        }
    }
    Ok(())
}

async fn run_schedule(action: &ScheduleAction, agent: &str, json: bool) -> anyhow::Result<()> {
    use crate::core::nervous::cron::parse_schedule_file;

    let base = dirs::home_dir()
        .unwrap_or_default()
        .join(".souveraine")
        .join("agents")
        .join(agent)
        .join("memory")
        .join("schedules");

    if !base.exists() {
        std::fs::create_dir_all(&base)?;
    }

    match action {
        ScheduleAction::List => {
            let mut found = false;
            if let Ok(entries) = std::fs::read_dir(&base) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if path.extension().map(|e| e == "md").unwrap_or(false) {
                        if let Ok(e) = parse_schedule_file(&path) {
                            found = true;
                            if json {
                                println!("{}", serde_json::to_string(&e).unwrap_or_default());
                            } else {
                                println!(
                                    "  {} ({:?}, {}, {})",
                                    e.name,
                                    e.kind,
                                    e.schedule,
                                    if e.enabled { "enabled" } else { "disabled" }
                                );
                            }
                        }
                    }
                }
            }
            if !found && !json {
                println!("No schedules found.");
            }
        }

        ScheduleAction::Status => {
            let state_path = base.join(".state.json");
            if state_path.exists() {
                let data = std::fs::read_to_string(&state_path)?;
                println!("{data}");
            } else if json {
                println!("{{}}");
            } else {
                println!("No schedule state yet.");
            }
        }

        ScheduleAction::Create { name, cron, interval, prompt } => {
            let file_path = base.join(format!("{name}.md"));
            if file_path.exists() {
                anyhow::bail!("schedule '{name}' already exists");
            }

            let (kind, sched) = if let Some(c) = cron {
                ("cron", c.clone())
            } else if let Some(i) = interval {
                ("interval", i.to_string())
            } else {
                ("interval", "3600".to_string())
            };

            let content = format!(
                "---\nname: {name}\nkind: {kind}\nschedule: \"{sched}\"\nsource: user\nenabled: true\nurgency: 0.3\ncreated_at: {}\n---\n\n{prompt}\n",
                chrono::Utc::now().to_rfc3339()
            );
            std::fs::write(&file_path, content)?;

            if json {
                println!(r#"{{"status":"created","name":"{name}"}}"#);
            } else {
                println!("Schedule '{name}' created.");
            }
        }

        ScheduleAction::Delete { name } => {
            let file_path = base.join(format!("{name}.md"));
            if !file_path.exists() {
                anyhow::bail!("schedule '{name}' not found");
            }
            std::fs::remove_file(&file_path)?;
            if json {
                println!(r#"{{"status":"deleted","name":"{name}"}}"#);
            } else {
                println!("Schedule '{name}' deleted.");
            }
        }

        ScheduleAction::Run { name } => {
            let file_path = base.join(format!("{name}.md"));
            if !file_path.exists() {
                anyhow::bail!("schedule '{name}' not found");
            }
            let trigger = base.join(format!(".trigger-{name}"));
            std::fs::write(&trigger, "")?;
            if json {
                println!(r#"{{"status":"triggered","name":"{name}"}}"#);
            } else {
                println!("Schedule '{name}' triggered — will fire on next tick.");
            }
        }
    }
    Ok(())
}

async fn run_tui(
    config: Arc<RwLock<ConsciousnessConfig>>,
    agent_pref: String,
) -> anyhow::Result<()> {
    let mut app = App::new(config, agent_pref);
    app.run().await?;
    Ok(())
}

/// Resolve the backend per `--local` and remote health.
///
/// - `--local` forces in-process LocalBackend (no network attempt).
/// - Otherwise: probe the remote URL; on success use Remote, on failure
///   transparently fall back to Local. The constitution's sovereignty principle
///   (Article VI.1) says the harness must keep working when the server is gone.
async fn resolve_backend(
    config: &Arc<RwLock<ConsciousnessConfig>>,
    force_local: bool,
    json: bool,
    quiet: bool,
) -> anyhow::Result<(Box<dyn crate::backend::Backend>, &'static str)> {
    use crate::backend::{Backend, LocalBackend, RemoteBackend};

    if force_local {
        let cfg = config.read().await.clone();
        let local = LocalBackend::new(cfg).await?;
        if !json && !quiet {
            eprintln!("  (local mode — engine in-process)");
        }
        return Ok((Box::new(local), "local"));
    }

    let server_url = config.read().await.server.effective_url();
    let remote = RemoteBackend::new(&server_url);
    if remote.health().await {
        return Ok((Box::new(remote), "remote"));
    }

    if !json && !quiet {
        eprintln!("  (no server at {} — falling back to local)", server_url);
    }
    let cfg = config.read().await.clone();
    let local = LocalBackend::new(cfg).await?;
    Ok((Box::new(local), "local"))
}

async fn run_chat(
    config: Arc<RwLock<ConsciousnessConfig>>,
    agent_name: String,
    message: Option<String>,
    json: bool,
    quiet: bool,
    force_local: bool,
) -> anyhow::Result<()> {
    use crate::backend::BackendEvent;
    use futures::StreamExt;

    let (backend, mode) = resolve_backend(&config, force_local, json, quiet).await?;

    // Resolve the agent: if `--agent` matches a name on the backend, use its id.
    let agents = backend.list_agents().await?;
    let resolved = agents.iter().find(|a| a.name == agent_name || a.id == agent_name)
        .or_else(|| agents.first());
    let agent = match resolved {
        Some(a) => a.clone(),
        None => {
            let hint = if mode == "local" {
                "No agents in local store. Create one via POST /v1/agents (server mode) or souveraine init."
            } else {
                "No agents on the server. Create one via POST /v1/agents."
            };
            if json { println!(r#"{{"status":"no-agents"}}"#); } else { eprintln!("{}", hint); }
            return Ok(());
        }
    };

    let conv_id = backend.ensure_conversation(&agent.id).await?;

    let one_shot = message.clone();
    if let Some(msg) = one_shot {
        let mut stream = backend.send(&conv_id, &msg).await?;
        if !json { println!("\n  {}: {}\n", agent.name, msg); print!("  "); }
        let mut full = String::new();
        while let Some(ev) = stream.next().await {
            match ev? {
                BackendEvent::Token(t) => {
                    if json { /* collect */ } else {
                        use std::io::Write;
                        print!("{}", t);
                        std::io::stdout().flush().ok();
                    }
                    full.push_str(&t);
                }
                BackendEvent::Reasoning(r) => {
                    if !json { eprintln!("\n  [thinking] {}", r); }
                }
                BackendEvent::Surfacing { source, content, .. } => {
                    if !json { eprintln!("\n  [{}] {}", source, content); }
                }
                BackendEvent::Done => break,
                _ => {}
            }
        }
        if json {
            let out = serde_json::json!({"agent": agent.name, "response": full});
            println!("{}", serde_json::to_string_pretty(&out)?);
        } else {
            println!();
        }
        return Ok(());
    }

    // Interactive REPL
    println!("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!("  Souveraine — {} ({} mode)", agent.name, mode);
    println!("  /exit to leave");
    println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
    let mut rl = rustyline::DefaultEditor::new().ok();
    loop {
        let prompt = format!("{}> ", agent.name);
        let line = match rl.as_mut() {
            Some(r) => r.readline(&prompt).ok(),
            None => None,
        };
        let Some(input) = line else { break };
        let input = input.trim().to_string();
        if input.is_empty() { continue; }
        if matches!(input.as_str(), "/exit" | "/quit" | "/q") { break; }
        if let Some(r) = rl.as_mut() { r.add_history_entry(&input).ok(); }

        let mut stream = backend.send(&conv_id, &input).await?;
        print!("\n  {}: ", agent.name);
        use std::io::Write;
        std::io::stdout().flush().ok();
        while let Some(ev) = stream.next().await {
            match ev? {
                BackendEvent::Token(t) => { print!("{}", t); std::io::stdout().flush().ok(); }
                BackendEvent::Reasoning(r) => eprintln!("\n  [thinking] {}", r),
                BackendEvent::Surfacing { source, content, .. } => eprintln!("\n  [{}] {}", source, content),
                BackendEvent::Done => break,
                _ => {}
            }
        }
        println!("\n");
    }
    println!("bye");
    Ok(())
}

async fn run_reflect(
    config: Arc<RwLock<ConsciousnessConfig>>,
    agent_name: String,
    conversation: Option<String>,
    json: bool,
) -> anyhow::Result<()> {
    use crate::backend::LocalBackend;
    let cfg = config.read().await.clone();
    let local = LocalBackend::new(cfg).await?;
    let server = local.server();

    let summaries = server.agents.list(None).await?;
    let agent = summaries
        .iter()
        .find(|a| a.name == agent_name || a.id == agent_name)
        .or_else(|| summaries.first())
        .ok_or_else(|| anyhow::anyhow!("no agents configured"))?;

    // Resolve a conversation. Explicit --conversation wins; otherwise
    // pick the most recent active conversation for this agent.
    let store = crate::core::conversation::ConversationStore::new(
        &dirs::home_dir()
            .unwrap_or_default()
            .join(".souveraine")
            .join("agents")
            .join(&agent.id),
    );
    let conv_id = match conversation {
        Some(id) => id,
        None => {
            let mut records = store.list_active().await?;
            records.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
            records
                .into_iter()
                .next()
                .map(|r| r.id)
                .ok_or_else(|| {
                    anyhow::anyhow!("no conversations found for agent '{}'", agent.id)
                })?
        }
    };

    let messages = store.load_messages(&conv_id).await?;
    if messages.is_empty() {
        anyhow::bail!("conversation '{conv_id}' has no messages to reflect on");
    }

    if !json {
        println!(
            "Reflecting on conversation {} ({} messages) for agent {}…",
            &conv_id[..8.min(conv_id.len())],
            messages.len(),
            agent.name,
        );
    }

    let report = server
        .consciousness
        .reflection()
        .reflect_now(&agent.id, &messages)
        .await?;

    if json {
        println!("{}", serde_json::to_string_pretty(&report)?);
    } else {
        println!();
        println!("─── Reflection complete ─────────────────────────────");
        println!("  agent:           {}", report.agent_id);
        println!("  turns reviewed:  {}", report.turns_reviewed);
        println!(
            "  duration:        {:.1}s",
            (report.completed_at - report.started_at)
                .num_milliseconds() as f64 / 1000.0
        );
        println!(
            "  exited cleanly:  {}",
            if report.exited_cleanly { "yes" } else { "no (tool rounds exhausted)" }
        );
        println!("─────────────────────────────────────────────────────");
        println!();
        println!("{}", report.summary);
    }

    Ok(())
}

async fn run_agents(
    config: Arc<RwLock<ConsciousnessConfig>>,
    json: bool,
    force_local: bool,
) -> anyhow::Result<()> {
    let (backend, mode) = resolve_backend(&config, force_local, json, false).await?;
    let agents = backend.list_agents().await?;
    if json {
        let payload: Vec<_> = agents.iter().map(|a| serde_json::json!({
            "id": a.id, "name": a.name, "description": a.description,
        })).collect();
        println!("{}", serde_json::to_string_pretty(&serde_json::json!({"agents": payload}))?);
    } else {
        println!("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        println!("  Agents ({} mode)", mode);
        println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        if agents.is_empty() {
            println!("  (none — POST /v1/agents to create one)");
        }
        for a in &agents {
            println!("  {}  {}", a.id, a.name);
            if let Some(d) = &a.description { println!("    {}", d); }
        }
        println!();
    }
    Ok(())
}


async fn run_status(config: Arc<RwLock<ConsciousnessConfig>>, json: bool) -> anyhow::Result<()> {
    let cfg = config.read().await;

    if json {
        let output = serde_json::json!({
            "bifrost_url": cfg.bifrost.base_url,
            "primary_model": cfg.bifrost.primary_model,
            "memory": {
                "git_enabled": cfg.memory.git_enabled,
                "auto_commit": cfg.memory.auto_commit,
            },
            "subconscious": {
                "n1_enabled": cfg.subconscious.n1_enabled,
                "inbox_enabled": cfg.subconscious.inbox_enabled,
            },
            "reflection": {
                "enabled": cfg.reflection.enabled,
                "message_interval": cfg.reflection.message_interval,
                "trigger": format!("{:?}", cfg.reflection.trigger),
            },
            "archivist": {
                "enabled": cfg.archivist.enabled,
                "interval": cfg.archivist.interval,
                "threshold": cfg.archivist.threshold,
                "compression_model": cfg.archivist.compression_model,
            },
            "models_configured": cfg.models.len(),
        });
        println!("{}", serde_json::to_string_pretty(&output)?);
    } else {
        println!("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        println!("  Souveraine — World State");
        println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        println!("  Bifrost:       {}", cfg.bifrost.base_url);
        println!("  Voice:         {}", cfg.bifrost.primary_model);
        println!("  Memory:        git={}, auto_commit={}", cfg.memory.git_enabled, cfg.memory.auto_commit);
        println!("  N+1:           enabled={}, inbox={}", cfg.subconscious.n1_enabled, cfg.subconscious.inbox_enabled);
        println!("  Reflection:    enabled={}, every {} messages", cfg.reflection.enabled, cfg.reflection.message_interval);
        println!("  Archivist:     enabled={}, every {} msgs at {} pressure",
            cfg.archivist.enabled, cfg.archivist.interval, cfg.archivist.threshold);
        println!("  Compresses via: {}", cfg.archivist.compression_model);
        println!("  Models known:  {}", cfg.models.len());
        println!();
    }
    Ok(())
}

async fn run_server(
    bind_override: Option<String>,
    port_override: Option<u16>,
    config: Arc<RwLock<ConsciousnessConfig>>,
) -> anyhow::Result<()> {
    println!("Starting Souveraine server...");

    let cfg = config.read().await.clone();
    let bind = bind_override.unwrap_or_else(|| cfg.server.bind.clone());
    let port = port_override.unwrap_or(cfg.server.port);

    let server = server::SouveraineServer::new(cfg).await?;

    {
        let mut server_config = server.config.write().await;
        server_config.bind = bind;
        server_config.port = port;
    }

    server.run().await
}

// ─── Config loading ─────────────────────────────────────────────────────────

async fn load_config() -> anyhow::Result<ConsciousnessConfig> {
    let config_paths = [
        PathBuf::from("souveraine.toml"),
        PathBuf::from("souveraine.yaml"),
        PathBuf::from("~/.config/souveraine/config.toml"),
        PathBuf::from("~/.config/souveraine/config.yaml"),
    ];

    for path in &config_paths {
        let path_str = path.to_string_lossy();
        let expanded = shellexpand::tilde(&path_str);
        let path = PathBuf::from(expanded.as_ref());

        if path.exists() {
            info!("loading config from {:?}", path);
            return ConsciousnessConfig::load(&path);
        }
    }

    warn!("no config found; using defaults (will probe Bifrost for models)");
    let config = ConsciousnessConfig::default();

    // Try to seed model list from Bifrost
    info!("discovering models from Bifrost");
    let bifrost = bridge::BifrostClient::new(
        &config.bifrost.base_url,
        &config.bifrost.api_key,
        &config.bifrost.virtual_key,
        &config.bifrost.primary_model,
    );
    match bifrost.list_models().await {
        Ok(models) => {
            info!("{} models available via Bifrost", models.len());
            for m in models {
                debug!("  {}", m);
            }
        }
        Err(e) => warn!("could not reach Bifrost: {}", e),
    }

    Ok(config)
}
